# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JigsawPuzzle' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'PuzzleMaker'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'Firebase/Core'
  pod ‘FirebaseInstanceID’, ‘2.0.4’
  pod 'Firebase/Messaging'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Fabric'
  pod 'Crashlytics'
end
